### ISSUE TITLE
这个好像没有 禁止刷新的功能,我要用这个功能,应该怎么解决呢 

### ISSUE THREAD

**Issue by xinyangcuncun** [REBOOTERS/UltimateRefreshView#4]

**Comment by REBOOTERS** [comment]
不调用setXXXAdapter 方法，即可禁用对应的刷新功能。

**Comment by xinyangcuncun** [comment]
我的意思是 调用了之后 比如列表加载完成了,我应该怎么禁止下拉功能,或者是再替换个布局去显示加载完成呢

**Comment by REBOOTERS** [comment]
现有的功能，是根据用户手势决定上下拉时的动画效果，而不是数据（列表加载完成，对View来说是无法预知的），你要明白view这个道理，如果要实现你所说的功能，需要做更复杂的设计。
